CREATE TABLE `listings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`unitCode` varchar(32) NOT NULL,
	`titleAr` text NOT NULL,
	`titleEn` text NOT NULL,
	`developer` varchar(128) NOT NULL,
	`project` varchar(128) NOT NULL,
	`location` varchar(256) NOT NULL,
	`unitType` varchar(64) NOT NULL DEFAULT 'Apartment',
	`area` int NOT NULL,
	`rooms` int NOT NULL,
	`toilets` int NOT NULL,
	`downpayment` varchar(64) NOT NULL DEFAULT '0',
	`monthlyInst` varchar(64) NOT NULL DEFAULT '',
	`price` varchar(64) NOT NULL,
	`finishing` varchar(64) NOT NULL DEFAULT 'Semi Finished',
	`delivery` varchar(64) NOT NULL DEFAULT '',
	`featured` int NOT NULL DEFAULT 0,
	`areaSlug` varchar(64) NOT NULL DEFAULT 'new-capital',
	`images` text,
	`sortOrder` int NOT NULL DEFAULT 0,
	`active` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `listings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
