-- Elite Homes — Supabase schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)

-- Listings (all units)
CREATE TABLE IF NOT EXISTS public.listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_code TEXT,
  -- Bilingual: prefer title_ar first, fallback title_en (auto-translated if missing)
  title_ar TEXT,
  title_en TEXT,
  developer_ar TEXT,
  developer_en TEXT,
  project_ar TEXT,
  project_en TEXT,
  location TEXT,
  unit_type TEXT DEFAULT 'Apartment',
  area INT,
  rooms INT,
  toilets INT,
  downpayment TEXT,
  monthly_inst TEXT,
  price TEXT,
  finishing TEXT,
  delivery TEXT,
  featured BOOLEAN DEFAULT false,
  area_slug TEXT NOT NULL DEFAULT 'new-capital', -- 'new-capital' | 'new-cairo'
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Listing images (Supabase Storage URLs or external URLs)
CREATE TABLE IF NOT EXISTS public.listing_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES public.listings(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Analytics: unit visibility, CTA clicks, photo browsed
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT REFERENCES public.listings(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL, -- 'view' | 'cta_whatsapp' | 'cta_call' | 'photo_view' | 'lead'
  payload JSONB DEFAULT '{}', -- e.g. { "photo_index": 2 }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for analytics and listing queries
CREATE INDEX IF NOT EXISTS idx_analytics_listing_id ON public.analytics_events(listing_id);
CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON public.analytics_events(created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_event_type ON public.analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_listings_area_slug ON public.listings(area_slug);
CREATE INDEX IF NOT EXISTS idx_listings_featured ON public.listings(featured);

-- RLS: allow public read for listings and listing_images; allow insert for analytics_events
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.listing_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Drop policies if they exist so migration can be re-run safely
DROP POLICY IF EXISTS "Public read listings" ON public.listings;
DROP POLICY IF EXISTS "Public read listing_images" ON public.listing_images;
DROP POLICY IF EXISTS "Anyone can insert analytics" ON public.analytics_events;
DROP POLICY IF EXISTS "Public read analytics" ON public.analytics_events;
DROP POLICY IF EXISTS "Allow all listings for now" ON public.listings;
DROP POLICY IF EXISTS "Allow all listing_images for now" ON public.listing_images;

CREATE POLICY "Public read listings" ON public.listings FOR SELECT USING (true);
CREATE POLICY "Public read listing_images" ON public.listing_images FOR SELECT USING (true);
CREATE POLICY "Anyone can insert analytics" ON public.analytics_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read analytics" ON public.analytics_events FOR SELECT USING (true);

-- Control panel: use service_role key in backend or add auth later. For now, control page uses password gate; write to Supabase from frontend with anon key. We need policies for admin.
-- Option A: Create a separate schema or use service_role from a server. Option B: Allow insert/update/delete for listings and listing_images only from authenticated users. Since we're using password gate only (no Supabase Auth), we need to either use a Supabase Edge Function that checks a secret, or allow with a limited anon policy. Simplest: allow all for development; user can restrict by RLS later with Supabase Auth.
-- For password-only admin, the frontend will use the anon key. So we need to allow UPDATE/INSERT/DELETE on listings and listing_images. That's insecure if anon key is public. Best practice: use Supabase Auth (email/password or magic link) for admin and RLS policies that allow only authenticated users to mutate. I'll add policies that allow all for now and add a comment that they should switch to Auth + RLS for production.
CREATE POLICY "Allow all listings for now" ON public.listings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all listing_images for now" ON public.listing_images FOR ALL USING (true) WITH CHECK (true);

-- Storage bucket for listing images (create in Dashboard; cannot be created via SQL):
-- 1. Supabase Dashboard → Storage → New bucket
-- 2. Name exactly: listing-images  (no spaces, hyphen)
-- 3. Public bucket: ON (so listing images are viewable)
-- 4. Create bucket, then run: npm run upload-images

COMMENT ON TABLE public.listings IS 'Elite Homes listings; title_ar required, title_en can be auto-translated';
COMMENT ON TABLE public.analytics_events IS 'Tracks view, cta_whatsapp, cta_call, photo_view, lead (1 per session, matches Google) per listing';
