-- Multi-site: Elite Homes, Arabian Estate, etc. — same Supabase

-- 1. Sites table
CREATE TABLE IF NOT EXISTS public.sites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  whatsapp_number TEXT,
  phone_number TEXT,
  theme_color TEXT DEFAULT '#c9a84c',
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add site_id to listings
ALTER TABLE public.listings ADD COLUMN IF NOT EXISTS site_id BIGINT REFERENCES public.sites(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_listings_site_id ON public.listings(site_id);

-- 3. Add site_id to analytics_events
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS site_id BIGINT REFERENCES public.sites(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_analytics_site_id ON public.analytics_events(site_id);

-- 4. Seed default sites
INSERT INTO public.sites (id, name, slug, whatsapp_number, phone_number)
VALUES (1, 'Elite Homes', 'elite-homes', '201025735135', '+201025735135')
ON CONFLICT (id) DO NOTHING;
INSERT INTO public.sites (id, name, slug, whatsapp_number, phone_number)
VALUES (2, 'Arabian Estate', 'arabian-estate', '201025735135', '+201025735135')
ON CONFLICT (id) DO NOTHING;

-- 5. Backfill: existing listings → Elite Homes (site_id 1)
UPDATE public.listings SET site_id = 1 WHERE site_id IS NULL;

-- 6. Backfill: existing analytics → get site from listing
UPDATE public.analytics_events ae
SET site_id = l.site_id
FROM public.listings l
WHERE ae.listing_id = l.id AND ae.site_id IS NULL;

-- 7. RLS for sites
ALTER TABLE public.sites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read sites" ON public.sites;
CREATE POLICY "Public read sites" ON public.sites FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow all sites for now" ON public.sites;
CREATE POLICY "Allow all sites for now" ON public.sites FOR ALL USING (true) WITH CHECK (true);
